name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: ruby getHomeBrewJson.rb
      - run: ruby getRepologyJson.rb
      
      # Setup chron for timing
      # Setup PRs to be made against HomeBrew
