name: Schedule CI
on:
  schedule: # Setup cron for timing
  - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: ruby getHomeBrewJson.rb
      - run: ruby getRepologyJson.rb
      - run: ruby compareHomeBrewAndRepology.rb

      # Setup PRs to be made against HomeBrew
