name: Schedule CI
on:
  schedule: # Setup cron for timing
    - cron: '0 */4 * * *' # at 0 minutes past every 4th hr
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: ruby printPackageUpdates.rb

      # Setup PRs to be made against HomeBrew
